### ISSUE TITLE
real

### ISSUE THREAD

**Issue by pathoes** [killerkong24/Syracuse-4.0#7]
a skid client built off Syracuse but aims to fix most of the issues present in Syracuse-v3.0
already fixed most of the issues present in the latest build which will never be released

(overall it being a shit client with a bad owner and worse modules) by adding some code of my own and modules of my own
ur code and modules are skidded and shit, "worse modules" is because the source leak is 3 months outdated LOL
i do admit im a bad owner but dont call my client shit when its 3 months outdated and when u couldnt do anything better

**Comment by Volcan4436** [comment]
> a skid client built off Syracuse but aims to fix most of the issues present in Syracuse-v3.0 already fixed most of the issues present in the latest build which will never be released
> 
> (overall it being a shit client with a bad owner and worse modules) by adding some code of my own and modules of my own ur code and modules are skidded and shit, "worse modules" is because the source leak is 3 months outdated LOL i do admit im a bad owner but dont call my client shit when its 3 months outdated and when u couldnt do anything better

Saying your client isn't shit when you put no work into the client is funny are you hear all night
